FROM node:16-alpine as build

RUN apk --no-cache add --update git

WORKDIR /usr/main/

RUN yarn set version 2 --only-if-needed

COPY frontend/package.json ./package.json
COPY frontend/yarn.lock ./yarn.lock
COPY frontend/vite.config.ts ./vite.config.ts
COPY frontend/tsconfig.json ./tsconfig.json
COPY frontend/tsconfig.node.json ./tsconfig.node.json

COPY frontend/index.html ./index.html
COPY frontend/src/* ./src/*

RUN yarn

CMD ["yarn", "build"]