FROM node:16-alpine as build

RUN apk --no-cache add --update git

WORKDIR /usr/main/

RUN yarn set version 2 --only-if-needed

COPY backend/package.json ./package.json
COPY backend/package-lock.json ./package-lock.json
COPY backend/yarn.lock ./yarn.lock
COPY backend/tsconfig.json ./tsconfig.json
COPY backend/tsconfig.build.json ./tsconfig.build.json

COPY backend/nest-cli.json ./nest-cli.json

COPY backend/src* ./src/

RUN yarn

RUN yarn build

CMD ["node", "dist/main.js"]